import json
import os

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "settings.json")

with open(CONFIG_PATH, "r", encoding="utf-8") as file:
    settings = json.load(file)

ENVIRONMENT = os.getenv("ENVIRONMENT", "produccion").lower()

if ENVIRONMENT not in settings:
    raise ValueError(f"El entorno '{ENVIRONMENT}' no existe")

URLS = settings[ENVIRONMENT]

CHILE_URL_ENTEL_HOGAR_INTERNET = URLS["CHILE_URL_ENTEL_HOGAR_INTERNET"]
PERU_URL_ENTEL_HOME = URLS["PERU_URL_ENTEL_HOME"]
PERU_URL_ENTEL_HOGAR_INTERNET = URLS["PERU_URL_ENTEL_HOGAR_INTERNET"]
CHILE_URL_ENTEL_HOGAR_DOBLEPACK = URLS["CHILE_URL_ENTEL_HOGAR_DOBLEPACK"]
CHILE_URL_ENTEL_HOGAR_TRIPLEPACK = URLS["CHILE_URL_ENTEL_HOGAR_TRIPLEPACK"]
CHILE_URL_ENTEL_HOGAR_TV = URLS["CHILE_URL_ENTEL_HOGAR_TV"]
CHILE_URL_ENTEL_RECOMENDADOR = URLS["CHILE_URL_ENTEL_RECOMENDADOR"]
CHILE_URL_ENTEL_MOVIL_PORTABILIDAD = URLS["CHILE_URL_ENTEL_MOVIL_PORTABILIDAD"]
PERU_URL_ENTEL_MOVIL = URLS["PERU_URL_ENTEL_MOVIL"]
CHILE_URL_ENTEL_MOVIL_PLAN_ADICIONAL = URLS["CHILE_URL_ENTEL_MOVIL_PLAN_ADICIONAL"]
CHILE_URL_ENTEL_OFERTAS_MOVIL = URLS["CHILE_URL_ENTEL_OFERTAS_MOVIL"]
CHILE_URL_ENTEL_HOME = URLS["CHILE_URL_ENTEL_HOME"]
PERU_URL_ENTEL_MOVIL_LINEAS_ADICIONALES = URLS[
    "PERU_URL_ENTEL_MOVIL_LINEAS_ADICIONALES"
]
CHILE_URL_ENTEL_MOVIL_LINEA_NUEVA = URLS["CHILE_URL_ENTEL_MOVIL_LINEA_NUEVA"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_01 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_01"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_02 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_02"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_03 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_03"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_04 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_04"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_05 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_05"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_06 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_06"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_07 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_07"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_08 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_08"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_09 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_09"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_10 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_10"]
PERU_URL_ENTEL_OFERTAS_PROMOCIONES_11 = URLS["PERU_URL_ENTEL_OFERTAS_PROMOCIONES_11"]
PERU_URL_ENTEL_TELEFONIA_FIJA = URLS["PERU_URL_ENTEL_TELEFONIA_FIJA"]
PERU_URL_ENTEL_PREPAGO_BOLSAS = URLS["PERU_URL_ENTEL_PREPAGO_BOLSAS"]
PERU_URL_ENTEL_PREPAGO_PLANES = URLS["PERU_URL_ENTEL_PREPAGO_PLANES"]
PERU_URL_ENTEL_PREPAGO_RECARGAS = URLS["PERU_URL_ENTEL_PREPAGO_RECARGAS"]
PERU_URL_ENTEL_PREPAGO_BENEFICIOS = URLS["PERU_URL_ENTEL_PREPAGO_BENEFICIOS"]
PERU_URL_ENTEL_RECAMBIOPOWER = URLS["PERU_URL_ENTEL_RECAMBIOPOWER"]
PERU_URL_ENTEL_SEGUROS = URLS["PERU_URL_ENTEL_SEGUROS"]
PERU_URL_ENTEL_CHIP_AUTOACTIVADO = URLS["PERU_URL_ENTEL_CHIP_AUTOACTIVADO"]
PERU_URL_ENTEL_APPLE = URLS["PERU_URL_ENTEL_APPLE"]
PERU_URL_ENTEL_AYUDA = URLS["PERU_URL_ENTEL_AYUDA"]
PERU_URL_ENTEL_TIENDAS = URLS["PERU_URL_ENTEL_TIENDAS"]
PERU_URL_ENTEL_INFO_ABONADOS = URLS["PERU_URL_ENTEL_INFO_ABONADOS"]

print(f"Entorno: {ENVIRONMENT.upper()}")
