import json
import os

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "settings.json")

with open(CONFIG_PATH, "r", encoding="utf-8") as file:
    settings = json.load(file)

ENVIRONMENT = os.getenv("ENVIRONMENT", "produccion").lower()

if ENVIRONMENT not in settings:
    raise ValueError(f"El entorno '{ENVIRONMENT}' no existe")

URLS = settings[ENVIRONMENT]

CHILE_URL_ENTEL_HOGAR_INTERNET = URLS["CHILE_URL_ENTEL_HOGAR_INTERNET"]
PERU_URL_ENTEL_HOME = URLS["PERU_URL_ENTEL_HOME"]
PERU_URL_ENTEL_HOGAR_INTERNET = URLS["PERU_URL_ENTEL_HOGAR_INTERNET"]
CHILE_URL_ENTEL_HOGAR_DOBLEPACK = URLS["CHILE_URL_ENTEL_HOGAR_DOBLEPACK"]
CHILE_URL_ENTEL_HOGAR_TRIPLEPACK = URLS["CHILE_URL_ENTEL_HOGAR_TRIPLEPACK"]
CHILE_URL_ENTEL_HOGAR_TV = URLS["CHILE_URL_ENTEL_HOGAR_TV"]
CHILE_URL_ENTEL_RECOMENDADOR = URLS["CHILE_URL_ENTEL_RECOMENDADOR"]
CHILE_URL_ENTEL_MOVIL_PORTABILIDAD = URLS["CHILE_URL_ENTEL_MOVIL_PORTABILIDAD"]
PERU_URL_ENTEL_MOVIL = URLS["PERU_URL_ENTEL_MOVIL"]
CHILE_URL_ENTEL_MOVIL_PLAN_ADICIONAL = URLS["CHILE_URL_ENTEL_MOVIL_PLAN_ADICIONAL"]
CHILE_URL_ENTEL_OFERTAS_MOVIL = URLS["CHILE_URL_ENTEL_OFERTAS_MOVIL"]
CHILE_URL_ENTEL_HOME = URLS["CHILE_URL_ENTEL_HOME"]
PERU_URL_ENTEL_MOVIL_LINEAS_ADICIONALES = URLS[
    "PERU_URL_ENTEL_MOVIL_LINEAS_ADICIONALES"
]
CHILE_URL_ENTEL_MOVIL_LINEA_NUEVA = URLS["CHILE_URL_ENTEL_MOVIL_LINEA_NUEVA"]

print(f"Entorno: {ENVIRONMENT.upper()}")
